#!/usr/bin/env bash
# Fastbit PCB — Export review pack for a pull request
#
# Generates the artifacts a reviewer needs to evaluate a PR:
#   - Schematic PDF
#   - BOM CSV
#   - ERC report
#   - DRC report
#   - 3D render (if KiCad supports it in the current environment)
#
# Manual artifacts (layout screenshots) still have to be generated by the
# engineer from the KiCad GUI and dropped into design/pcb/outputs/review_pack/.
# This script creates the folder and produces the scriptable artifacts only.
#
# Usage:
#   ./scripts/export_review_pack.sh
#
# Per SOP-HW-001 §7.7.1 (PCB PR template).

set -euo pipefail

KICAD_PROJECT_DIR="design/pcb/kicad"
SCHEMATIC="$KICAD_PROJECT_DIR/Swasthik_KiBot_Project.kicad_sch"
PCB="$KICAD_PROJECT_DIR/Swasthik_KiBot_Project.kicad_pcb"
OUTPUTS_DIR="design/pcb/outputs/review_pack"

mkdir -p "$OUTPUTS_DIR"

echo "=============================="
echo "Fastbit PCB — Review pack export"
echo "=============================="
echo "Output directory: $OUTPUTS_DIR"
echo ""

# -----------------------------------------------------------------------------
# 1. Schematic PDF
# -----------------------------------------------------------------------------
if [ -f "$SCHEMATIC" ]; then
  echo "[1/5] Exporting schematic PDF..."
  kicad-cli sch export pdf \
    --output "$OUTPUTS_DIR/schematic.pdf" \
    "$SCHEMATIC"
  echo "      OK: $OUTPUTS_DIR/schematic.pdf"
else
  echo "[1/5] SKIP: schematic not found at $SCHEMATIC"
fi

# -----------------------------------------------------------------------------
# 2. BOM CSV
# -----------------------------------------------------------------------------
if [ -f "$SCHEMATIC" ]; then
  echo "[2/5] Exporting BOM..."
  kicad-cli sch export bom \
    --output "$OUTPUTS_DIR/bom.csv" \
    "$SCHEMATIC"
  echo "      OK: $OUTPUTS_DIR/bom.csv"
else
  echo "[2/5] SKIP: schematic not found, cannot export BOM"
fi

# -----------------------------------------------------------------------------
# 3. ERC report
# -----------------------------------------------------------------------------
if [ -f "$SCHEMATIC" ]; then
  echo "[3/5] Running ERC..."
  if kicad-cli sch erc \
      --output "$OUTPUTS_DIR/erc_report.txt" \
      --severity-error --severity-warning \
      "$SCHEMATIC" 2>&1; then
    echo "      OK: $OUTPUTS_DIR/erc_report.txt"
  else
    echo "      WARN: ERC found issues — report written to $OUTPUTS_DIR/erc_report.txt"
  fi
else
  echo "[3/5] SKIP: schematic not found"
fi

# -----------------------------------------------------------------------------
# 4. DRC report
# -----------------------------------------------------------------------------
if [ -f "$PCB" ]; then
  echo "[4/5] Running DRC..."
  if kicad-cli pcb drc \
      --output "$OUTPUTS_DIR/drc_report.txt" \
      --severity-error --severity-warning \
      "$PCB" 2>&1; then
    echo "      OK: $OUTPUTS_DIR/drc_report.txt"
  else
    echo "      WARN: DRC found issues — report written to $OUTPUTS_DIR/drc_report.txt"
  fi
else
  echo "[4/5] SKIP: PCB not found at $PCB"
fi

# -----------------------------------------------------------------------------
# 5. Reminder to generate screenshots manually
# -----------------------------------------------------------------------------
echo "[5/5] Manual screenshots:"
SCREENSHOT_COUNT=$(find "$OUTPUTS_DIR" -maxdepth 1 -name '*.png' -o -name '*.jpg' 2>/dev/null | wc -l)
if [ "$SCREENSHOT_COUNT" -eq 0 ]; then
  echo ""
  echo "      REMINDER: No layout screenshots in $OUTPUTS_DIR yet."
  echo "      Open KiCad pcbnew, take screenshots of the affected areas, and save them here as:"
  echo ""
  echo "        - placement_<area>.png  (for stage: placement)"
  echo "        - routing_<area>.png    (for stage: routing)"
  echo "        - plane_<layer>.png     (for plane integrity review)"
  echo ""
  echo "      Per SOP §7.7.1, screenshots are MANDATORY for any layout change PR."
else
  echo "      Found $SCREENSHOT_COUNT screenshot file(s) in $OUTPUTS_DIR"
fi

echo ""
echo "=============================="
echo "Review pack export complete."
echo "=============================="
echo ""
echo "Next steps:"
echo "  1. Add any manual screenshots to $OUTPUTS_DIR"
echo "  2. Commit the review pack: git add $OUTPUTS_DIR && git commit -m 'Update review pack'"
echo "  3. Open your PR and fill in the template using the artifacts in $OUTPUTS_DIR"
